We submit that the RIAA is unauthorized to act on behalf of its member companies on matters involving the DMCA takedown of youtube-dl.
github/dmca pull request #8127
Opened 2020-10-23 23:27 UTC by sickcodes

October 24, 2020 

GitHub

Dear Sir or Madam:

I am contacting you on behalf of the community and its avid members. Sick Codes is a security 
research group has no member companies. Without prejudice save as to costs, we submit that the 
RIAA is unauthorized to act on behalf of its member companies on matters involving the DMCA takedown of youtube-dl. https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA.md

Copyright Violations.
We have learned that your service is hosting the following source codes
on its network at the following locations, among others:

https://github.com/youtube/youtube-chat-for-minecraft
Explicitty suggests using YouTube inside Minecraft.

https://github.com/youtube/yt-direct-lite-iOS
Explicity suggests saving videos to library that may upset recording artists that are members of the RIAA:
"Click Save Video to store the image in the library."

https://github.com/youtube/yt-auto-curate-ruby
Explicity suggests to "automatically "watch" a list of videos and take action when a new video is found that meets certain criteria."

https://github.com/youtube/yt-auto-curate-ruby
Explicity suggests to "automatically "watch" a list of videos and take action when a new video is found that meets certain criteria."

https://github.com/youtube/yt-watchme
Explicity suggests "creating a YouTube Live Streaming event and streams into that event.""

https://github.com/youtube/yt-android-player
Explicity suggests creating:
* A simple YouTube Android API demo application which shows how to create a simple application that
* displays a YouTube Video in a {@link YouTubePlayerView}.

https://github.com/youtube/yt-direct-lite-android
Explicity suggests using "an Android OS application that captures video, uploads it to YouTube"
This could be used to violate the rights of any user, anywhere, who does not wish to be filmed.

The above list includes a teeny, tiny, sample of the source code being hosted on GitHub.

Based on our review of the representative sample noted above, we have a good faith belief that 
most of the above repositories are infringing to the same extent as the parent repository.

The clear purpose of this source code is to (i) circumvent the technological protection measures
used by authorized streaming services such as YouTube, and (ii) reproduce and distribute music
videos and sound recordings owned by our member companies without authorization for such
use. We note that the source code is described on GitHub as “a command-line program to
download videos from YouTube.com and a few more sites.”1

We also note that the source
code prominently includes example use of the source code the downloading of copies of our
members’ copyrighted sound recordings and music videos, as noted in Exhibit A hereto. For
example, as shown on Exhibit A, the source code expressly suggests its use to copy and/or
distribute the following copyrighted works owned by our member companies:

https://github.com/youtube/youtubechatbot
http://yourprojectid.appspot.com/?videoId=xxxxx

The source code notes that the various works on YouTube are licensed under the YouTube Standard
license, which expressly restricts access to copyrighted works only for streaming on YouTube
and prohibits their further reproduction or distribution without consent of the copyright owner;
without authorization of the copyright owner or YouTube.

We have a good faith belief that this activity is not authorized by the copyright owner, its agent,
or the law. We assert that the information in this notification is accurate, based upon the data
available to us.

Anticircumvention Violation. We also note that the provision or trafficking of the source code
violates 17 USC §§1201(a)(2) and 1201(b)(1). The source code is a technology primarily
designed or produced for the purpose of, and marketed for, circumventing a technological
measure that effectively controls access to copyrighted sound recordings on YouTube, including
copyrighted sound recordings owned by our members. For further context, please see the
attached court decision from the Hamburg Regional Court that describes the technological
measure at issue (known as YouTube’s “rolling cipher”), and the court’s determination that the
technology employed by YouTube is an effective technical measure within the meaning of EU

Indeed, the code in the any of the source repos above make clear that the source code was
designed and is marketed for the purpose of circumventing YouTube’s technological measures
to enable unauthorized access to our member’s copyrighted works, and to make unauthorized
copies and distributions thereof: they identify our member’s works, they note that the works
are VEVO videos (virtually all of which are owned by our member companies), they
acknowledge the those works are licensed to YouTube under the YouTube standard license, and
they use those examples in the source code to describe how to obtain unauthorized access to
copies of our members’ works.

In light of the above noted copyright infringements and anticircumvention violations, we ask
that you immediately take down and disable access to the the above source code at all of its
locations where it is hosted on GitHub, including without limitation those locations in the
representative list set forth above.

This e-mail does not constitute a waiver of any right to recover damages incurred by virtue of
any such unauthorized activities, and all such rights as well as claims for other relief are
expressly reserved.

You may contact me on Twitter @sickcodes [twitter.com/sickcodes](twitter.com/sickcodes),  

Sincerely,  
@sickcodes

2020-10-24 00:27 UTC, Roki100 approved these changes

2020-10-24 00:39 UTC, Cyberboss approved these changes

2020-10-24 00:56 UTC, DiegoFleitas approved these changes

2020-10-24 00:57 UTC, antiops approved these changes

2020-10-24 00:57 UTC, VoltrexMaster approved these changes

2020-10-24 00:59 UTC, robbyoconnor approved these changes

2020-10-24 01:04 UTC, JakubVanek approved these changes

2020-10-24 01:07 UTC, Zandario approved these changes

2020-10-24 01:17 UTC, urmum-69 approved these changes

2020-10-24 01:38 UTC, IMS212 approved these changes

2020-10-24 01:46 UTC, TurboBiscuit approved these changes

2020-10-24 01:48 UTC, aboutDavid approved these changes

2020-10-24 01:48 UTC, RemiixInc approved these changes

2020-10-24 01:58 UTC, G2G2G2G approved these changes

2020-10-24 01:58 UTC, GalladeGuy approved these changes

2020-10-24 01:59 UTC, simontime approved these changes

2020-10-24 02:00 UTC, Gimzie approved these changes

2020-10-24 02:06 UTC, kiiwiiwastaken approved these changes

2020-10-24 02:08 UTC, GRAnimated approved these changes

2020-10-24 02:11 UTC, bremea approved these changes

2020-10-24 02:12 UTC, pcr910303 approved these changes

2020-10-24 02:19 UTC, oldLucke approved these changes

2020-10-24 02:20 UTC, tyan-boot approved these changes

2020-10-24 02:22 UTC, RektWithStyle approved these changes

2020-10-24 02:22 UTC, oldLucke requested changes

2020-10-24 02:22 UTC, oldLucke commented on 2020/10/2020-10-23-SICKCODES
> +Explicity suggests to "automatically "watch" a list of videos and take action when a new video is found that meets certain criteria."
duplicated line

2020-10-24 02:25 UTC, bparker06 approved these changes

2020-10-24 02:40 UTC, marshyonline approved these changes

2020-10-24 02:41 UTC, newaccountnewlife approved these changes

2020-10-24 02:44 UTC, shirt-dev approved these changes

2020-10-24 02:47 UTC, sickcodes commented on 2020/10/2020-10-23-SICKCODES
> +Explicity suggests to "automatically "watch" a list of videos and take action when a new video is found that meets certain criteria."
Thx, will fix shortly

2020-10-24 03:04 UTC, Doges approved these changes

2020-10-24 03:21 UTC, Tomoneko-Kuroki approved these changes

2020-10-24 03:44 UTC, vitalyster approved these changes

2020-10-24 03:57 UTC, Techinicabor approved these changes

2020-10-24 04:07 UTC, IanDuncanT approved these changes

2020-10-24 04:16 UTC, polarisfm approved these changes

2020-10-24 04:48 UTC, NoMod-Programming approved these changes

2020-10-24 05:01 UTC, sabbyX approved these changes

2020-10-24 05:03 UTC, Johnanater approved these changes

2020-10-24 05:35 UTC, JellyBrick approved these changes

2020-10-24 05:37 UTC, VideoGameSmash12 approved these changes

2020-10-24 05:57 UTC, Hexhu commented on 2020/10/2020-10-23-SICKCODES
> +download videos from YouTube.com and a few more sites.”1
An extra "1" after the end of the sentence

2020-10-24 06:34 UTC, darkRaspberry approved these changes

2020-10-24 07:00 UTC, eemunni approved these changes

2020-10-24 07:59 UTC, abhiTronix approved these changes

2020-10-24 08:13 UTC, RubenNL approved these changes

2020-10-24 08:26 UTC, lukgth approved these changes

2020-10-24 09:04 UTC, cybrefox approved these changes

2020-10-24 09:06 UTC, hexandcube approved these changes

2020-10-24 09:07 UTC, Foxaxe22 approved these changes

2020-10-24 09:14 UTC, yekknos approved these changes

2020-10-24 10:08 UTC, coggy9 approved these changes

2020-10-24 10:47 UTC, rbnkrnn approved these changes

2020-10-24 11:05 UTC, andrew77768 approved these changes

2020-10-24 11:22 UTC, bgette approved these changes
PERFECT!!

2020-10-24 11:24 UTC, ondrej008 approved these changes

2020-10-24 11:46 UTC, InspectorGilbert approved these changes

2020-10-24 11:49 UTC, Leoz83 approved these changes

2020-10-24 11:55 UTC, modscleo4 approved these changes

2020-10-24 12:34 UTC, RiversideRocks approved these changes

2020-10-24 12:43 UTC, ProjectRevoTPP approved these changes

2020-10-24 12:55 UTC, KangDroid approved these changes

2020-10-24 13:38 UTC, KurtBestor approved these changes

2020-10-24 13:58 UTC, SaidBySolo approved these changes

2020-10-24 14:10 UTC, RektWithStyle approved these changes

2020-10-24 14:11 UTC, LoveCany approved these changes

2020-10-24 14:13 UTC, derNiklaas approved these changes

2020-10-24 14:15 UTC, signalhunter approved these changes

2020-10-24 14:19 UTC, iomintz commented
This repository is unmonitored. If your goal here was to reach GitHub, you should contact the YouTube DL developers and ask them to reach out to GitHub.

Why does your "representative sample" only contain official Google code? Google owns YouTube so why would it be infringing?

2020-10-24 14:22 UTC, MoartMedia approved these changes

2020-10-24 14:31 UTC, mid-kid approved these changes

2020-10-24 14:36 UTC, iomintz commented
Everyone please stop approving the changes if you agree. There's hundreds of people watching this repository and we all get a notification each time you do so. If you agree with the changes a 👍 reaction on the first post is sufficient.

2020-10-24 14:51 UTC, darkRaspberry commented
> Everyone please stop approving the changes if you agree. There's hundreds of people watching this repository and we all get a notification each time you do so. If you agree with the changes a  reaction on the first post is sufficient.

There is option for unsubscribe.

2020-10-24 14:53 UTC, MrDoritos approved these changes

2020-10-24 14:56 UTC, Techinicabor commented
I dont use my email for much so I find it pretty funny. Sorry if you don't.

2020-10-24 15:17 UTC, IanDuncanT requested changes
Fix 1 at end of line 46

2020-10-24 15:55 UTC, l1ving approved these changes

2020-10-24 17:04 UTC, stefan-it commented
Dear RIAA: Fu** you!

2020-10-24 17:47 UTC, NickAcPT approved these changes

2020-10-24 18:15 UTC, rikupacito approved these changes

2020-10-24 19:19 UTC, stefan-it approved these changes

2020-10-24 19:41 UTC, aeiouaeiouaeiouaeiouaeiouaeiou approved these changes

2020-10-24 21:00 UTC, dvtate approved these changes

2020-10-24 21:06 UTC, iomintz commented
> There is option for unsubscribe.
@darkRaspberry 
I think I will, since people don't seem to be making meaningful comments or using the reaction buttons instead of reviews.

2020-10-24 22:15 UTC, 0x450x6c approved these changes

2020-10-24 23:57 UTC, EnderDev approved these changes

2020-10-25 00:16 UTC, curlpipe approved these changes

2020-10-25 01:14 UTC, DiegoFleitas commented
Everyone please approve the changes if you agree. I'm one of the hundreds of people watching this repository and we all get a notification each time you do so. I laugh every time and It's keeping me sane in this quarantine

2020-10-25 01:42 UTC, l1ving approved these changes

2020-10-25 02:55 UTC, IMS212 approved these changes

2020-10-25 03:16 UTC, iczero approved these changes

2020-10-25 03:34 UTC, williamd1k0 approved these changes

2020-10-25 04:08 UTC, zeroday0619 approved these changes

2020-10-25 05:57 UTC, erkinalp approved these changes

2020-10-25 06:07 UTC, nathang21 approved these changes

2020-10-25 06:31 UTC, niyumard approved these changes

2020-10-25 06:50 UTC, ilsubyeega approved these changes

2020-10-25 07:05 UTC, eshack94 approved these changes

2020-10-25 08:02 UTC, sickcodes commented
@stephen304 pushed the youtube-dl source code as a PR to this repo and deleted his branch so nobody can remove it 🤣🤣🤣🤣 I'm fucking done

https://github.com/github/dmca/pull/8142

2020-10-25 08:03 UTC, Diffumist approved these changes

2020-10-25 08:22 UTC, database64128 approved these changes

2020-10-25 08:29 UTC, 0xbkt approved these changes
LGTM.

2020-10-25 09:11 UTC, negezor approved these changes

2020-10-25 10:44 UTC, angelobreuer requested changes
Some typos

2020-10-25 10:44 UTC, angelobreuer commented on 2020/10/2020-10-23-SICKCODES
> +research group has no member companies. Without prejudice save as to costs, we submit that the
```suggestion
research group that has no member companies. Without prejudice save as to costs, we submit that the 
```

2020-10-25 10:44 UTC, angelobreuer commented on 2020/10/2020-10-23-SICKCODES
> +Explicitty suggests using YouTube inside Minecraft.
```suggestion
Explicitly suggests using YouTube inside Minecraft.
```

2020-10-25 10:44 UTC, angelobreuer commented on 2020/10/2020-10-23-SICKCODES
> +Explicity suggests saving videos to library that may upset recording artists that are members of the RIAA:
```suggestion
Explicitly suggests saving videos to library that may upset recording artists that are members of the RIAA:
```

2020-10-25 10:44 UTC, angelobreuer commented on 2020/10/2020-10-23-SICKCODES
> +Explicity suggests to "automatically "watch" a list of videos and take action when a new video is found that meets certain criteria."
```suggestion
Explicitly suggests to "automatically "watch" a list of videos and take action when a new video is found that meets certain criteria."
```

2020-10-25 10:44 UTC, angelobreuer commented on 2020/10/2020-10-23-SICKCODES
> +Explicity suggests "creating a YouTube Live Streaming event and streams into that event.""
```suggestion
Explicitly suggests "creating a YouTube Live Streaming event and streams into that event.""
```

2020-10-25 10:44 UTC, angelobreuer commented on 2020/10/2020-10-23-SICKCODES
> +Explicity suggests creating:
```suggestion
Explicitly suggests creating:
```

2020-10-25 10:44 UTC, angelobreuer commented on 2020/10/2020-10-23-SICKCODES
> +Explicity suggests using "an Android OS application that captures video, uploads it to YouTube"
```suggestion
Explicitly suggests using "an Android OS application that captures video, uploads it to YouTube"
```

2020-10-25 10:44 UTC, angelobreuer commented on 2020/10/2020-10-23-SICKCODES
> +Indeed, the code in the any of the source repos above make clear that the source code was
```suggestion
Indeed, the code in any of the source repos above make clear that the source code was
```

2020-10-25 10:44 UTC, angelobreuer commented on 2020/10/2020-10-23-SICKCODES
> +acknowledge the those works are licensed to YouTube under the YouTube standard license, and
```suggestion
acknowledge those works are licensed to YouTube under the YouTube standard license, and
```

2020-10-25 10:44 UTC, angelobreuer commented on 2020/10/2020-10-23-SICKCODES
> +that you immediately take down and disable access to the the above source code at all of its
```suggestion
that you immediately take down and disable access to the above source code at all of its
```

2020-10-25 12:15 UTC, gluons approved these changes

2020-10-25 12:30 UTC, gordon-zhao approved these changes

2020-10-25 12:49 UTC, Navid2zp approved these changes

2020-10-25 12:52 UTC, Snowflake107 approved these changes

2020-10-25 13:01 UTC, TheChosenEvilOne approved these changes

2020-10-25 13:34 UTC, MeguminSama approved these changes

2020-10-25 13:40 UTC, dhtdht020 approved these changes

2020-10-25 14:12 UTC, code-rgb approved these changes

2020-10-25 14:16 UTC, saqsham approved these changes

2020-10-25 14:16 UTC, dequeues approved these changes

2020-10-25 14:18 UTC, 00p513-dev approved these changes

2020-10-25 14:34 UTC, IanDuncanT requested changes
Fix typos

2020-10-25 15:01 UTC, elisaado commented
merge with the changes from @angelobreuer lgtm

2020-10-25 15:30 UTC, Jackojc approved these changes

2020-10-25 17:13 UTC, sickcodes commented
> merge with the changes from @angelobreuer lgtm

Will do tomorrow

2020-10-25 17:15 UTC, imachug approved these changes

2020-10-25 17:36 UTC, GrimReaperFloof approved these changes

2020-10-25 18:03 UTC, btwiusegentoo approved these changes

2020-10-25 18:56 UTC, immibis commented
you guys this isn't how DMCA works

2020-10-25 18:58 UTC, DominykasPetke approved these changes

2020-10-25 19:19 UTC, Krutonium commented
> you guys this isn't how DMCA works

Nobody Cares, the idea is to make noise so that someone with lawyers might take notice, like Microsoft.

2020-10-25 20:25 UTC, lululombard approved these changes

2020-10-25 20:51 UTC, sickcodes commented
> you guys this isn't how DMCA works

DRM doesn't work

2020-10-25 22:44 UTC, skoskav approved these changes

2020-10-26 00:45 UTC, dgw commented on 2020/10/2020-10-23-SICKCODES
> +download videos from YouTube.com and a few more sites.”1
```suggestion
download videos from YouTube.com and a few more sites.”
```

2020-10-26 05:45 UTC, NoMod-Programming approved these changes

2020-10-26 10:54 UTC, MeguminSama approved these changes

2020-10-26 10:55 UTC, analotia approved these changes

2020-10-26 11:00 UTC, analotia approved these changes

2020-10-26 11:00 UTC, analotia approved these changes

2020-10-26 12:33 UTC, StelFux approved these changes

2020-10-26 13:19 UTC, Crysicia approved these changes

2020-10-26 18:58 UTC, digmorepaka approved these changes

2020-10-27 00:22 UTC, akimy approved these changes

2020-10-27 11:07 UTC, vitalkanev commented
This repository does not accept user pull requests. Developer should consider filing a counter notice instead.

2020-10-27 14:50 UTC, IanDuncanT requested changes
Fix typos as listed in comments.

2020-10-27 16:44 UTC, abhiTronix commented
https://sfconservancy.org/blog/2020/oct/26/microsoft-github-riaa-youtube-dl/

2020-10-27 23:40 UTC, Yoruroong approved these changes

2020-10-28 00:21 UTC, geonizeli approved these changes

2020-10-28 04:14 UTC, andinue approved these changes

2020-10-28 04:27 UTC, Noctfield approved these changes

2020-10-28 16:55 UTC, jessephus commented
Hi 👋🏽  We are closing this pull request, because we [do not accept contributions](https://github.com/github/dmca/blob/master/CONTRIBUTING.md) to this repository. Feel free to keep the discussion going in this thread. Please just be mindful to keep the discussion respectful and consistent with [GitHub’s Community Guidelines](https://docs.github.com/github/site-policy/github-community-guidelines).

We understand that you may have questions about this takedown. Although we do not normally monitor comments posted to this repository, our team is reading through the comments and questions in this and other recent threads to see where we may be able to clarify our policies or answer some common questions. Thanks.

2020-10-28 16:55 UTC, closed without merging

2020-10-28 16:59 UTC, shirt-dev commented
> Hi 👋🏽 We are closing this pull request, because we [do not accept contributions](https://github.com/github/dmca/blob/master/CONTRIBUTING.md) to this repository. Feel free to keep the discussion going in this thread. Please just be mindful to keep the discussion respectful and consistent with [GitHub’s Community Guidelines](https://docs.github.com/github/site-policy/github-community-guidelines).
> 
> We understand that you may have questions about this takedown. Although we do not normally monitor comments posted to this repository, our team is reading through the comments and questions in this and other recent threads to see where we may be able to clarify our policies or answer some common questions. Thanks.

Can you clarify how that DMCA is legitimate?

2020-10-28 18:17 UTC, garymoon commented
> Can you clarify how that DMCA is legitimate?

Relevant: [The RIAA’s fraudulent attack on youtube-dl is not a DMCA §512 infringement/safe-harbour, and the reality is weird](https://joindiaspora.com/posts/808cf690f8e801381778002590d8e506)

Even if it were agreed that the repository contained examples of how to commit copyright infringement with the tool, why should the project not be afforded the opportunity to rectify that and continue on?

2020-10-28 18:35 UTC, darkRaspberry commented
> > you guys this isn't how DMCA works
> 
> Nobody Cares, the idea is to make noise so that someone with lawyers might take notice, like Microsoft.

Look like they noticed and closed this.
This is seriously very bad.

2020-10-29 00:32 UTC, Cellularhacker commented
I have no idea why they closed this Thread.
This is really really really really bad situation

2020-10-29 13:28 UTC, Hans5958 commented
Ladies and gentlemen, may I have your attention on this court order added hours ago?

https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA-court-order.pdf

2020-10-30 14:57 UTC, sickcodes commented
> Ladies and gentlemen, may I have your attention on this court order added hours ago?
> 
> 
> 
> https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA-court-order.pdf

Is that file 3 years old? Why are they uploading it now?

2020-11-03 12:09 UTC, Testsr commented
> > Ladies and gentlemen, may I have your attention on this court order added hours ago?
> > https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA-court-order.pdf
> 
> Is that file 3 years old? Why are they uploading it now?

To prove that a case against similar behavior has been successful before. If it show that, I am not sure. BTW removing this notice, does not remove any DMCA claims.

2020-11-17 00:06 UTC, VideoGameSmash12 commented
HAHAHAHAHAHA

2020-11-17 00:06 UTC, VideoGameSmash12 commented
HAHAHAHAHAHAHAHA
https://github.com/github/dmca/blob/master/2020/11/2020-11-16-RIAA-reversal-effletter.pdf

2020-11-17 00:34 UTC, sickcodes commented
Reopen please, let alone merge thx 💚

2020-11-17 00:34 UTC, sickcodes commented
FYI anyone subbed here who doesn't know yet, YouTube-dl back!

2020-11-17 10:42 UTC, Hans5958 commented
UPDATE: It's official, RIAA just got their L. youtube-dl is back, boys!

GitHub's statement:
- https://github.blog/2020-11-16-standing-up-for-developers-youtube-dl-is-back/
- https://twitter.com/GitHubPolicy/status/1328365918750003203
- https://twitter.com/natfriedman/status/1328365679473426432

youtube-dl's statement: ytdl-org/youtube-dl#27013

DMCA reversal letter:
- https://github.com/github/dmca/blob/master/2020/11/2020-11-16-RIAA-reversal-effletter.pdf
- https://github.com/github/dmca/commit/e00bfb544e93bfd3066fe1699171964dd2dc29e0

(for those who aren't aware and future readers)