[README] Arctic Code Vault & DMCA Chilling effects
github/dmca pull request #8131
Opened 2020-10-24 04:50 UTC by sickcodes

#### What about code stored in the Arctic Code Vault?
We do not automatically remove content stored in the [Artic Code Vault](https://archiveprogram.github.com/) as code stored in the vault has already been frozen and therefore not subject to *Chilling Effects*.

2020-10-24 05:46 UTC, Thuruv approved these changes

2020-10-24 15:58 UTC, l1ving approved these changes

2020-10-24 16:00 UTC, polarisfm approved these changes

2020-10-24 19:51 UTC, Margen67 approved these changes

2020-10-25 21:15 UTC, L33Tech approved these changes

2020-10-26 05:30 UTC, bkhl approved these changes

2020-10-26 09:51 UTC, alexis-evelyn approved these changes

2020-10-26 12:35 UTC, StelFux approved these changes

2020-10-27 02:53 UTC, Nefomemes approved these changes
Finally a real and not troll pull request.

2020-10-27 20:59 UTC, kubapolish approved these changes

2020-10-27 21:59 UTC, samuei approved these changes

2020-10-28 17:56 UTC, jessephus commented
Hi :wave: We are closing this pull request because we [do not accept contributions](https://github.com/github/dmca/blob/master/CONTRIBUTING.md) to this repository. Feel free to keep the discussion going in this thread. Please just be mindful to keep the discussion respectful and consistent with [GitHub’s Community Guidelines](https://docs.github.com/github/site-policy/github-community-guidelines).

We understand that you may have questions about this takedown. Although we do not normally monitor comments posted to this repository, our team is reading through the comments and questions in this and other recent threads to see where we may be able to clarify our policies or answer some common questions. In particular, we recognize that this pull request is making a serious suggestion, and we will consider clarifying this point in the near future.  Thanks.

2020-10-28 17:56 UTC, closed without merging

2024-09-30 08:53 UTC, EricMujjona requested changes
Good work